### ISSUE TITLE
Spec filepath when watched code changes incorrect with certain file extensions

### ISSUE THREAD

**Issue by nickbrowne** [keithpitty/guard-konacha-rails#9]
Given a coffeescript file:
```
app/javascripts/my_file.coffee
```
With an associated test:
```
spec/javascripts/my_file_spec.coffee
```

Both files will be watched for changes correctly, but the associated test will not run when the watched `app/javascripts/my_file.coffee` changes.

It seems to be to do with the file extensions, as it seemed to work if the files had the file extension `.js.coffee` when I last ran into this issue this a few weeks ago. But, it's possible that my memory is wrong.

I may make a simple test app which demonstrates this issue if I have time later.

**Comment by keithpitty** [comment]
@nickbrowne can you confirm what the `guard 'konacha-rails'` snippet of your `Guardfile` contains?

**Comment by nickbrowne** [comment]
```ruby
guard 'konacha-rails', notification: false do
  watch(%r{^app/assets/javascripts/(.*)\.(js|coffee)?$}) { |m| "#{m[1]}_spec.js" }
  watch(%r{^(test|spec)/javascripts/.+_(test|spec)\.(js|coffee)$})
end
```

**Comment by keithpitty** [comment]
Ah, I suspect the template in `lib/guard/konacha-rails/templates/Guardfile` is incorrect. It is:

```ruby
guard 'konacha-rails' do
  watch(%r{^app/assets/javascripts/(.*)\.(js|coffee)?$}) { |m| "#{m[1]}_spec.js" }
  watch(%r{^(test|spec)/javascripts/.+_(test|spec)\.(js|coffee)$})
end
```

when it should be:

```ruby
guard 'konacha-rails' do
  watch(%r{^app/assets/javascripts/(.*)\.(js|coffee)?$}) { |m| "spec/javascripts/#{m[1]}_spec.js" }
  watch(%r{^(test|spec)/javascripts/.+_(test|spec)\.(js|coffee)$})
end
```

And, even then, you would want your snippet to be the following if you have `.coffee` specs:

```ruby
guard 'konacha-rails' do
  watch(%r{^app/assets/javascripts/(.*)\.coffee}) { |m| "spec/javascripts/#{m[1]}_spec.coffee" }
  watch(%r{^spec/javascripts/.+_spec\.coffee$})
end
```
